# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jretlang}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gareth Reeves"]
  s.date = %q{2011-08-30}
  s.description = %q{A JRuby package of jretlang}
  s.email = %q{reevesg@pobox.com}
  s.files = [
    "Rakefile",
    "VERSION",
    "changelog",
    "jretlang.gemspec",
    "lib/jretlang.rb",
    "lib/jretlang/channel.rb",
    "lib/jretlang/fiber.rb",
    "lib/jretlang/latch.rb",
    "readme",
    "test/unit/test_examples.rb",
    "test/unit/unit_test_helper.rb",
    "vendor/jetlang-0.2.5-sources.jar",
    "vendor/jetlang-0.2.5.jar"
  ]
  s.homepage = %q{http://github.com/reevesg/jretlang}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A JRuby package of jretlang}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

